version: "1"

description: "Manage Werk with Werk"

jobs:
  main:
    description: "Build application"
    executor: shell
    commands:
      - shards build
    needs:
      - lint
      - test

  lint:
    description: "Lint code"
    executor: shell
    commands:
      - ameba
    can_fail: true

  test:
    description: "Test code"
    executor: shell
    commands:
      - crystal spec

  deps:
    description: "Install dependencies"
    executor: shell
    commands:
      - brew install libssh2
      - shards install

  docs:
    description: Generate API documentation
    executor: shell
    commands:
      - crystal docs
      - open docs/index.html

  install:
    description: Install Werk locally
    executor: shell
    commands:
      - echo "Installing locally..."
      - sudo cp -v ./bin/werk /usr/local/bin
    needs:
      - main

  uninstall:
    description: Uninstall Werk locally
    executor: shell
    variables:
      APP: /usr/local/bin/werk
    commands:
      - '[[ -f "${APP}" ]] && sudo rm -vf "${APP}" || echo "Werk is not installed!"'

  bump-version:
    description: Update version
    executor: shell
    commands:
      - >
        if [ -z ${VERSION+x} ]; then
          echo "Missing variable VERSION!"
          echo "Please make sure the variable is set before running this target."
          exit 1
        fi
      - echo "Updating version ..."
      - yq eval -i ".version = \"${VERSION}\"" shard.yml
      - sed -i .bak "s/VERSION = \".*\"/VERSION = \"${VERSION}\"/" src/version.cr && rm src/version.cr.bak
      - echo "Done."
