version: "1"

jobs:
  main:
    executor: shell
    commands:
      - echo "This"
      - echo "...and that"
    silent: true
    needs:
      - other

  other:
    executor: shell
    commands:
      - echo "Other"
