name: CD

on:
  push:
    tags: [ "*" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Install prerequisites
        run: |
          brew install crystal

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install
      
      - name: Build
        run: shards build --release

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          brew update
          brew install crystal-lang

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: shards install
      
      - name: Build
        run: shards build --release --static

  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker build
        run: docker build -t marghidanu/werk  .
