name: CD

on:
  release:
    types:
      - published

jobs:
  build-docker:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kaniko builder
        uses: aevea/action-kaniko@v0.6.0
        with:
          image: boord/werk
          tag: ${{ github.event.release.tag_name }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: boord/werk

  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["macos-10.15", "macos-11.0", "ubuntu-18.04"]

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 0.35.1
      
      - name: Additional Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev
      
      - name: Additional macOS dependencies
        if: contains(matrix.os, 'macos')
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace version in shard file
        uses: datamonsters/replace-action@v2
        with:
          files: "shard.yml"
          replacements: "0.0.0=${{ github.event.release.tag_name }}"

      - name: Replace version in application
        uses: datamonsters/replace-action@v2
        with:
          files: "src/werk.cr"
          replacements: "0.0.0=${{ github.event.release.tag_name }}"

      - name: Build
        run: shards build --release --no-debug

      - name: Compute checksum
        run: sha256sum ./bin/werk | tee checksum.txt

      - name: Upload script
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/werk
          asset_name: werk-${{ matrix.os }}
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
