name: CI

on:
  push:
    tags-ignore: ["**"]
    branches: ["**"]
  schedule:
    - cron: 0 23 * * *

jobs:
  quality:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.1.0
  
  build-docker:
    runs-on: ubuntu-18.04

    needs:
      - quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kaniko builder
        uses: aevea/action-kaniko@v0.6.0
        with:
          image: boord/werk
          extra_args: --no-push

  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["macos-10.15", "ubuntu-20.04"]

    needs:
      - quality

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 0.36.0

      - name: Additional Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
