name: CI

on:
  - push
  - pull_request

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.1.0

  test-macos:
    runs-on: macos-latest
    needs: quality

    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"

    steps:
      - name: Install prerequisites
        run: brew install crystal

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec

  test-linux:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Install prerequisites
        run: |
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash -s -- --crystal=0.35.1
          apt install -y libyaml-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
