name: Crystal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          brew tap veelenga/tap
          brew install crystal ameba

      - name: Lint code
        run: ameba

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec

  linux:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.1-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: apk add --no-cache ameba

      - name: Lint code
        run: ameba

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
