name: Crystal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
