name: Crystal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.1.0

  macos:
    runs-on: macos-10.15

    needs: quality

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          brew tap veelenga/tap
          brew install crystal

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec

  linux:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.1-alpine

    needs: quality

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
