name: Crystal CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          brew tap veelenga/tap
          brew update 
          brew install crystal ameba
      
      - name: Lint code
        run: ameba

      - name: Install dependencies
        run: shards install
      
      - name: Run tests
        run: crystal spec

  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2

      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.1.0

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
